# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/joshu/Documents/DSD25_Termproject_Materials_Updated250519/00_RTL_Skeleton/dsd_termprj.srcs/sources_1/bd/design_1/ip/design_1_top_mlp_0_0/design_1_top_mlp_0_0.xci
# IP: The module: 'design_1_top_mlp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/joshu/Documents/DSD25_Termproject_Materials_Updated250519/00_RTL_Skeleton/dsd_termprj.srcs/sources_1/ip/dsp_macro_0/dsp_macro_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# XDC: c:/Users/joshu/Documents/DSD25_Termproject_Materials_Updated250519/00_RTL_Skeleton/dsd_termprj.gen/sources_1/bd/design_1/ip/design_1_top_mlp_0_0/design_1_top_mlp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_mlp_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/joshu/Documents/DSD25_Termproject_Materials_Updated250519/00_RTL_Skeleton/dsd_termprj.srcs/sources_1/bd/design_1/ip/design_1_top_mlp_0_0/design_1_top_mlp_0_0.xci
# IP: The module: 'design_1_top_mlp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/joshu/Documents/DSD25_Termproject_Materials_Updated250519/00_RTL_Skeleton/dsd_termprj.srcs/sources_1/ip/dsp_macro_0/dsp_macro_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# XDC: c:/Users/joshu/Documents/DSD25_Termproject_Materials_Updated250519/00_RTL_Skeleton/dsd_termprj.gen/sources_1/bd/design_1/ip/design_1_top_mlp_0_0/design_1_top_mlp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_mlp_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
