@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Apr 13 00:11:15 +0900 2026
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim top_mlp_tb_behav -key {Behavioral:sim_1:Functional:top_mlp_tb} -tclbatch top_mlp_tb.tcl -protoinst "protoinst_files/bd_48ac.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/test/vivadoproject/DSD25_Termproject_recursive/reculsive/00_RTL_Skeleton/top_mlp_tb_behav.wcfg -log simulate.log"
call xsim  top_mlp_tb_behav -key {Behavioral:sim_1:Functional:top_mlp_tb} -tclbatch top_mlp_tb.tcl -protoinst "protoinst_files/bd_48ac.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/test/vivadoproject/DSD25_Termproject_recursive/reculsive/00_RTL_Skeleton/top_mlp_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
